dist: trusty
sudo: false
language: node_js
node_js: '6'
os:
- linux
- osx
env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
before_install:
- openssl aes-256-cbc -K $encrypted_8307fd996c28_key -iv $encrypted_8307fd996c28_iv
  -in oauth2info.json.enc -out .oauth2info.json -d
install:
- npm install
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run build; npm run dist; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run build; npm run dist -- -mw; fi
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
notifications:
  email: false
  slack:
    secure: $SLACK_TOKEN
deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN
  skin_cleanup: true
  on:
    tags: true
